#!/bin/bash

# $1 is Domain
# $2 is Email

lines=(
    "events {}"
    "http {"
    "    upstream payload {"
    "        server payload:3001;"
    "    }"
    "    upstream next {"
    "        server next:3000;"
    "    }"
    "    server {"
    "        listen 80;"
    "        listen [::]:80;"
    "        server_name admin.$1;"
    "        "
    "        location / {"
    "            return 301 https://\$host\$request_uri;"
    "        }    location ~ /.well-known/acme-challenge {"
    "            allow all;"
    "            root /tmp/acme_challenge;"
    "        }"
    "    }"
    "    server {"
    "        listen 80;"
    "        listen [::]:80;"
    "        server_name $1;"
    "        "
    "        location / {"
    "            return 301 https://\$host\$request_uri;"
    "        }    location ~ /.well-known/acme-challenge {"
    "            allow all;"
    "            root /tmp/acme_challenge;"
    "        }"
    "    }"
    "    server {"
    "        listen 443 ssl;"
    "        listen [::]:443 ssl http2;"
    "        server_name $1;"
    "        "
    "        ssl_certificate /etc/letsencrypt/live/$1/fullchain.pem;"
    "        ssl_certificate_key /etc/letsencrypt/live/$1/privkey.pem;"
    "        "
    "        location / {"
    "            proxy_pass http://next;"
    "            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
    "            proxy_set_header Host \$host;"
    "            proxy_redirect off;"
    "        }    location /static/ {"
    "            alias /static/;"
    "        }"
    "    }"
    "    server {"
    "        listen 443 ssl;"
    "        listen [::]:443 ssl http2;"
    "        server_name admin.$1;"
    "        "
    "        ssl_certificate /etc/letsencrypt/live/admin.$1/fullchain.pem;"
    "        ssl_certificate_key /etc/letsencrypt/live/admin.$1/privkey.pem;"
    "        "
    "        location / {"
    "            proxy_pass http://payload;"
    "            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;"
    "            proxy_set_header Host \$host;"
    "            proxy_redirect off;"
    "        }    location /static/ {"
    "            alias /static/;"
    "        }"
    "    }"
    "}"
)
for ((i = 0; i < ${#lines[@]}; i++))
do
    printf '%b\n' "${lines[$i]}" >> ./nginx.conf
done